base_packages:
  - eza
  - fzf
  - neovim
  - lazygit
  - starship
  - zoxide
  - yazi
  - zellij
  - git
  - unzip
  - bat
  - kubectl
  - k9s
  - git-delta
  - ripgrep
  - postgresql
  - nodejs
  - npm

extra_packages: []

dotfiles_repo: https://github.com/terakael/dotfiles.git
dotfiles_dest: "{{ ansible_user_dir }}/dotfiles"

dotfiles_links:
  - src: "{{ ansible_user_dir }}/dotfiles/nvim"
    dest: "{{ ansible_user_dir }}/.config/nvim"
  - src: "{{ ansible_user_dir }}/dotfiles/starship.toml"
    dest: "{{ ansible_user_dir }}/.config/starship.toml"
  - src: "{{ ansible_user_dir }}/dotfiles/lazygit"
    dest: "{{ ansible_user_dir }}/.config/lazygit"
  - src: "{{ ansible_user_dir }}/dotfiles/k9s"
    dest: "{{ ansible_user_dir }}/.config/k9s"
  - src: "{{ ansible_user_dir }}/dotfiles/zellij"
    dest: "{{ ansible_user_dir }}/.config/zellij"
