- name: Base configuration (all hosts)
  hosts: all
  gather_facts: true
  roles:
    - base
    - dotfiles
    - rust

- name: WSL (work) configuration
  hosts: work
  gather_facts: true
  roles:
    - work

- name: Homelab configuration
  hosts: homelab
  gather_facts: true
  roles:
    - homelab
