- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: true

- name: reload user systemd
  systemd:
    daemon_reload: true
    scope: user

- name: restart ttyd
  systemd:
    name: ttyd
    state: restarted
    scope: user
