- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: true

- name: reload systemd
  systemd:
    daemon_reload: true
  become: true

- name: restart ttyd
  service:
    name: ttyd
    state: restarted
  become: true
