- name: Update pacman cache
  community.general.pacman:
    update_cache: true
  become: true

- name: Install base packages
  community.general.pacman:
    name: "{{ base_packages + extra_packages }}"
    state: present
  become: true
