- name: Update pacman cache
  community.general.pacman:
    update_cache: true
  become: true

- name: Install base packages
  community.general.pacman:
    name: "{{ base_packages + extra_packages }}"
    state: present
  become: true

- name: Ensure standard user directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ ansible_user_dir }}/.local/bin"
    - "{{ ansible_user_dir }}/.config"
    - "{{ ansible_user_dir }}/.screenshots"

- name: Configure bash aliases
  blockinfile:
    path: "{{ ansible_user_dir }}/.bash_aliases"
    create: true
    marker: "# {mark} ANSIBLE MANAGED: aliases"
    block: |
      alias lg="lazygit $*"
      alias l="eza --icons --color=always --long --all --no-user $*"
      alias k="kubectl $*"
      alias cd="z"
      alias cat="bat $*"
      alias vi="nvim $*"

- name: Configure bashrc
  blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    create: true
    marker: "# {mark} ANSIBLE MANAGED: shell config"
    block: |
      set -o vi
      eval "$(starship init bash)"
      eval "$(fzf --bash)"
      eval "$(zoxide init bash)"
      export EDITOR="nvim"
      export VISUAL="nvim"
      [ -f ~/.bash_aliases ] && source ~/.bash_aliases
