- name: Create Agave font directory
  file:
    path: /usr/share/fonts/agave
    state: directory
    mode: '0755'
  become: true

- name: Download Agave Nerd Font
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Agave.zip
    dest: /usr/share/fonts/agave/
    remote_src: true
    creates: /usr/share/fonts/agave/AgaveNerdFont-Regular.ttf
  become: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Refresh font cache
  command: fc-cache -f /usr/share/fonts/agave
  changed_when: false
  become: true
